#a) Create variable greet and store "welcome to a semester!" into great.
print("PE2_3")
greet=("welcome to a new semster!")
print(greet.capitalize())
#create variables first, last and use multiple assignment to store your first name in the first and last name in 
#last 
first, last ="kallissa", "Lazarus"
print (first)
#d) Use concatenation to store the data from first and last separated by a space into name.
name= first+' '+ last
print(name)
#e) use any of your three class in this term and use multiple assignments to store your classes in to class1, class2, and class3
